/*
 * Universidad del Valle Guatemala
 * CC3040 Bases de datos
 * Proyecto 1: DBMS
 * Jorge Estuardo Garcia 13175
 * Luis Humberto Duarte 13003
 * Kevin Eduardo Rivera 13389
 */

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;

//import org.antlr.v4.gui.Trees;
//import org.antlr.v4.gui.Trees;
import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Clase interfaz
 * @author Luis
 * @version 02/04/2016/A
 */
public class Consola extends javax.swing.JFrame {
    private EvalVisitor eval;

    /**
     * Creates new form Consola
     */
    public Consola() {
        initComponents();
        eval = new EvalVisitor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("SQL Editor", jScrollPane1);

        jScrollPane2.setViewportView(jTextPane1);

        jTabbedPane2.addTab("Data Output", jScrollPane2);

        jScrollPane3.setViewportView(jTextPane2);

        jTabbedPane2.addTab("Explain", jScrollPane3);

        jScrollPane4.setViewportView(jTextPane3);

        jTabbedPane2.addTab("Messages", jScrollPane4);

        jScrollPane5.setViewportView(jTextPane4);

        jTabbedPane2.addTab("History", jScrollPane5);

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jSeparator1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(evt.getSource()== jButton1){
             String parsear=jTextArea1.getText();
            //awevos que hay que cambiar esa direccion 
            ANTLRInputStream input = new ANTLRInputStream(parsear);

            // Create an Lexer that receives the char stream
            SqlLexer lexer = new SqlLexer(input);
            //lexer.removeErrorListeners();
            // Create a token stream from the lexer
            CommonTokenStream tokens = new CommonTokenStream(lexer);

        // Create a parser that receives the token stream
            SqlParser parser = new SqlParser(tokens);

            SqlParser.ProgramContext arbol = parser.program();

          /**  //Trees.inspect(arbol, parser);
            System.out.println("                                                     ");
            System.out.println("                                                     ");
            
            System.out.println("                                                     ");**/
            
        //	Trees.inspect(arbol, parser);
           
            eval.visitProgram(arbol);

          /*  System.out.println("                                                     ");
            System.out.println("                                                     ");
            */
            
            ArrayList data=eval.getControlador().getData();
            ArrayList log=eval.getControlador().getLog();
            ArrayList error=eval.getControlador().getError();
            jTextPane1.setText(arraytoString(data));
            jTextPane2.setText(arraytoString(log));
            jTextPane3.setText(arraytoString(error));
            eval.getControlador().setData(new ArrayList());
            eval.getControlador().setLog(new ArrayList());
            eval.getControlador().setError(new ArrayList());
            //jTextPane1.setText(arraytoString(data));
             //escribir(parsear);
           
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    public String arraytoString(ArrayList list){
        String resul=""; 
        for(int i=0; i<list.size(); i++){
            resul=resul+(String)list.get(i)+"\n";
        }
        return resul; 
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration                   
}

  
